language: ruby
sudo: false
script: 'ci/travis.rb'
before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"
before_script:
  - bundle update
cache: bundler
env:
  global:
    - JRUBY_OPTS='-J-Xmx1024M'
  matrix:
    - "GEM=railties"
    - "GEM=ap"
    - "GEM=am,amo,as,av,aj"
    - "GEM=ar:mysql"
    - "GEM=ar:mysql2"
    - "GEM=ar:sqlite3"
    - "GEM=ar:postgresql"
    - "GEM=aj:integration"
    - "GEM=guides"
rvm:
  - 2.2.2
  - ruby-head
  - rbx-2
  - jruby-head
matrix:
  allow_failures:
    - env: "GEM=ar:mysql"
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby-head
  fast_finish: true
notifications:
  hipchat: 6ahJuyZBj0QLlrVzAE9n6QCeHuthe38p1sRGiZGV@1649695
bundler_args: --without test --jobs 3 --retry 3
services:
  - memcached
  - redis
  - rabbitmq
addons:
  postgresql: "9.4.4"
