language: ruby
cache: bundler
rvm:
  - 2.2.2
before_install:
  - gem install bundler
  - rm ${BUNDLE_GEMFILE}.lock
  - gem update --system
  - gem --version
services:
  - redis-server
addons:
  postgresql: 9.3
script: bundle exec rake test
notifications:
  hipchat:
    rooms:
      secure: jCllFzOqfv5ng3ROz0Ft0SoZqkGDyg0TZPBAca7usUrXRXQCeQSfak8V3fkPskxSOii2I8CDcm4ubC474f8qVhx2UhndXBX//LZIg/hi8mmSB0iGaRpzTM/5XfgBHz38gv7+HXlSKZ69qZvXgGlVxD0YKVR6s5cn+xov7gllCtbQXORMU7NlxjE1AWGHKxWdwfpHjNQma85ylyhd1Eos+3jYtIKr6gxthZ9F7yjGs/cCqoKLOkIHwBZoxZry55h+8Vh6f5H6iJGDmQTe0icM4CTH8Zq5i4lAsekDauQN+7ra3NMk2fuib4mKGyPHLrvkO9lW2QHLUz+c7ykyQFpITkulo6MBfHIj+gEWE3V0Q/I1VUFkzwRI1MH4RkzmqyJhbCZgzQp08943W/vsGQ8f0HbyuYCwOM4yC5nKHXg0D1ZG/4skip0+psu7IIqYMTD4FiGgWNMmU363wV+Zv2OQHp/mzweplbh2yyaBx55NQYyxYlyCKC5jz0WSnC1lUiQP3UTcYbuJ5YplydMma6jvuFMeOEBvPdxugz1MKURwZGzjCQD2nXcmbHmsMo9TdreddBiv2WKKwkQXEDolWh1dIJs64ongrPFc9ZQGb2VBF8xOHcfsfpWT82QWmVIVyFdew5Bl8Sz/sbgNkNHH9GTCFypywqo9XarHAkVeWujQprU=
    notify: true
deploy:
  provider: heroku
  api_key:
    secure: HrfpZ3H3MJTSFTw1P3e4paeeEJUzlONxnP5cOUJ/Cu4C8vFaz6K7WYscZBzVGfiJYJfNv6GEPHBs77JjhKn2RYmxQ0NYdxoRhvUGKwahgs0XOEXa4LQps6hRnxV1NYFvut55CaO2fU4aLL6Qi+K1DQo+HmcVAHAtEXIpoIZ9Vyayf5wo3wQgNJel99hcaiJdOC73XTz+i2Qatoy4UTmldaNtSpt/UX29rQnWOiG/FAPk20nx9LJPpZLYbhMx24K4V/+F59U/7/Tc1nv6QOP492R1GZ1i6ey4dUROzsgzHaDs7TDV/gZubEXu+Mn7YXkRdnGR4tDff/Zz55DhMUpLFz49ry8k69GplWK5urxFcgDMKhZ8Gvrk+S6twGM9aOm9vD0Tf4yQQLUiv19i41IEhfSZVSHTiJNJ3dkUGeRMw7TmfTvIJhNSZRT54sr+1Ko+Baop5jvp5/5iGXmBednwgA8klBbxm6LoFDC4u31FRt8mQrVx5XrBH3FyprRotmPXPmLOpg2YMcXB2tiws4iVI4o7SDUMmPrcBM1CpRNQrzA4Gf06wFkvu+PBYsawrL1a261pQbNghsyVnVnxvZ5EplXvCnTe4CjisNevx22Jss0T0LCRqjxfRFw1xqXfhjdnZTQZowLghP7ZSnaHCTRjf2M5X+ZjbqIo3lKFz3qqao4=
  app: grox-mud
  on:
    repo: grox-org/mud
  run:
  - rake db:migrate
  - restart
  - rake cleanup
