language: ruby
cache: bundler
rvm:
- 2.2.2
before_install:
- gem install bundler
- rm ${BUNDLE_GEMFILE}.lock
- gem update --system
- gem --version
services:
- redis-server
addons:
  postgresql: 9.3
before_script:
- psql -c 'create database mud_test;' -U postgres
script: bundle exec rake test
notifications:
  hipchat:
    rooms:
      secure: QrwVGVkXGpdORHUd9mrcJJ7BbC5aUuHe2BVFLv89vc6G+P+1nOp7sAhpA+vnpy6q+6aE0Z9Z7j1ns56wd0E4oINoHniPh4pey5/bPVRaje02UHHN9ZOTPKpRfeDoX7lJiZsgc2LuP/AiKT4r/uDKK2L3/50FXZ4vQ52l2ekVLhxe9hACBaF1OEwNRV5JnfmTPEubbjrnx/2w1fckN7Bwsxh6s11WPSkj7i/fsIDjC7qmZjWD6/2HNmxBvFZaWUGqIvF+60GbPw8AN47T1/gCY38g4AgMRAd2cG/QMaTIlIxqP39NA7/0KnByq+6jF981x2CkoeYXsa55MD3KRIk3GyrGvtWDi8BqrUZSuMORws8kL+OXAYPDUd6k/8/08dig8d2G0njP0q/O1B0eGUIBELRzSvCfPC6hbXcOHGzEFKbfmzy5Jh7Twgqx+PiJ9kGzzNFOyh5VJyAxp2iTv6oyhE0pH9Nw2R33qNioomHhol9Bpas2/OrM4N4XkwakJvUFe+qPy6BXljpuXfRqUXOMf/PDHgbDf+o1NlCY0fKdlDG09sjpBZek/34Gb+ZBI4qKAtZAyspXNF8WNtjUEwaJCXg5fVy/k3W63eLU/dW+GAqWda0SVL9SMWf9AnOJSSmlMYIQ3tHBp24d8b4EU6oUhm6+GbN5HTI5fescksTRkXc=
    notify: true
deploy:
  provider: heroku
  api_key:
    secure: HrfpZ3H3MJTSFTw1P3e4paeeEJUzlONxnP5cOUJ/Cu4C8vFaz6K7WYscZBzVGfiJYJfNv6GEPHBs77JjhKn2RYmxQ0NYdxoRhvUGKwahgs0XOEXa4LQps6hRnxV1NYFvut55CaO2fU4aLL6Qi+K1DQo+HmcVAHAtEXIpoIZ9Vyayf5wo3wQgNJel99hcaiJdOC73XTz+i2Qatoy4UTmldaNtSpt/UX29rQnWOiG/FAPk20nx9LJPpZLYbhMx24K4V/+F59U/7/Tc1nv6QOP492R1GZ1i6ey4dUROzsgzHaDs7TDV/gZubEXu+Mn7YXkRdnGR4tDff/Zz55DhMUpLFz49ry8k69GplWK5urxFcgDMKhZ8Gvrk+S6twGM9aOm9vD0Tf4yQQLUiv19i41IEhfSZVSHTiJNJ3dkUGeRMw7TmfTvIJhNSZRT54sr+1Ko+Baop5jvp5/5iGXmBednwgA8klBbxm6LoFDC4u31FRt8mQrVx5XrBH3FyprRotmPXPmLOpg2YMcXB2tiws4iVI4o7SDUMmPrcBM1CpRNQrzA4Gf06wFkvu+PBYsawrL1a261pQbNghsyVnVnxvZ5EplXvCnTe4CjisNevx22Jss0T0LCRqjxfRFw1xqXfhjdnZTQZowLghP7ZSnaHCTRjf2M5X+ZjbqIo3lKFz3qqao4=
  app: grox-mud
  on:
    repo: grox-org/mud
  run:
  - rake db:migrate
  - restart
  - rake cleanup
