language: ruby
cache: bundler
rvm:
- 2.2.2
before_install:
- gem install bundler
- rm ${BUNDLE_GEMFILE}.lock
- gem update --system
- gem --version
sudo: required
services:
- redis-server
addons:
  postgresql: 9.3
  code_climate:
    repo_token: adf08323...
before_script:
- psql -c 'create database mud_test;' -U postgres
script: bundle exec rake test
notifications:
  email: false
  webhooks:
    secure: RUOUHxIbNd6fxr4KcFYlb16sHdVmcWwarI9otM0v/ssQukVMAdOGy6IDO3FGSzKQnh727VEAbKCTnXVS6DGXnA81EYeE/T/Lxe1kWUr2NuKdvg3OuQDtt0vLALhT/PYVGynDEANkq3OeQnl/Ll0cCxGYPyadC3tOYlfFJSR3wIP0j1ToA5WT4UP9Bhn6agnkGqSDxXe6zGo/+xGDK4B2JqBhqcfppukuWOBlMtB7D9SkDy8Cud0CfqRMKBdFleI1KEdVyVRSv9ZHA0ilPQ+TX2QW3TefwPm4K9QtGGk2MxTkTJOXNewFedOWBzNUvemjOXzSjwkCauHUzXxSGWLsB5aheKhr06EMHCsSi8J2i+wp+3m/seDrNP8jNnbjk7k5U22VJECrPEmTZOuG9mOB0EaNWr9Sht1BVoAycjX5p9m3x/ebFQ2gJEjJi6I1oRCJucIRmiejuUbSWTuCjBEixHoz7BVXFwDj8vdKb1Ut1WfAUlt3/3+9jiaNZ90SEBXxkNAU/LaY6yrL5uNFBNXMrr038kDs3UQgi7t74jgpbjv08MJLRH6kxPCI7Gzu70FAQ96x0+aBE7rhD2h40zifsFjEIjtJBjd2GoLEZxP+mYLqqncsd2xWGyM9+kqlg02vAG5/B1TJ+p1VIVVnsfrLGsQeWbwCmK7eLEfyNX5UHK8=
deploy:
  provider: heroku
  api_key:
    secure: HrfpZ3H3MJTSFTw1P3e4paeeEJUzlONxnP5cOUJ/Cu4C8vFaz6K7WYscZBzVGfiJYJfNv6GEPHBs77JjhKn2RYmxQ0NYdxoRhvUGKwahgs0XOEXa4LQps6hRnxV1NYFvut55CaO2fU4aLL6Qi+K1DQo+HmcVAHAtEXIpoIZ9Vyayf5wo3wQgNJel99hcaiJdOC73XTz+i2Qatoy4UTmldaNtSpt/UX29rQnWOiG/FAPk20nx9LJPpZLYbhMx24K4V/+F59U/7/Tc1nv6QOP492R1GZ1i6ey4dUROzsgzHaDs7TDV/gZubEXu+Mn7YXkRdnGR4tDff/Zz55DhMUpLFz49ry8k69GplWK5urxFcgDMKhZ8Gvrk+S6twGM9aOm9vD0Tf4yQQLUiv19i41IEhfSZVSHTiJNJ3dkUGeRMw7TmfTvIJhNSZRT54sr+1Ko+Baop5jvp5/5iGXmBednwgA8klBbxm6LoFDC4u31FRt8mQrVx5XrBH3FyprRotmPXPmLOpg2YMcXB2tiws4iVI4o7SDUMmPrcBM1CpRNQrzA4Gf06wFkvu+PBYsawrL1a261pQbNghsyVnVnxvZ5EplXvCnTe4CjisNevx22Jss0T0LCRqjxfRFw1xqXfhjdnZTQZowLghP7ZSnaHCTRjf2M5X+ZjbqIo3lKFz3qqao4=
  app: grox-mud
  on:
    repo: grox-org/mud
  run:
  - rake db:migrate
  - restart
