language: ruby
cache: bundler
rvm:
  - 2.2.2

before_install:
  - gem install bundler
  - rm ${BUNDLE_GEMFILE}.lock
  - gem update --system
  - gem --version

sudo: required
services:
  - redis-server
addons:
  postgresql: 9.3

before_script:
  - psql -c 'create database mud_test;' -U postgres
script: bundle exec rake test

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a5269257936c9426480a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

deploy:
  provider: heroku
  api_key:
    secure: HrfpZ3H3MJTSFTw1P3e4paeeEJUzlONxnP5cOUJ/Cu4C8vFaz6K7WYscZBzVGfiJYJfNv6GEPHBs77JjhKn2RYmxQ0NYdxoRhvUGKwahgs0XOEXa4LQps6hRnxV1NYFvut55CaO2fU4aLL6Qi+K1DQo+HmcVAHAtEXIpoIZ9Vyayf5wo3wQgNJel99hcaiJdOC73XTz+i2Qatoy4UTmldaNtSpt/UX29rQnWOiG/FAPk20nx9LJPpZLYbhMx24K4V/+F59U/7/Tc1nv6QOP492R1GZ1i6ey4dUROzsgzHaDs7TDV/gZubEXu+Mn7YXkRdnGR4tDff/Zz55DhMUpLFz49ry8k69GplWK5urxFcgDMKhZ8Gvrk+S6twGM9aOm9vD0Tf4yQQLUiv19i41IEhfSZVSHTiJNJ3dkUGeRMw7TmfTvIJhNSZRT54sr+1Ko+Baop5jvp5/5iGXmBednwgA8klBbxm6LoFDC4u31FRt8mQrVx5XrBH3FyprRotmPXPmLOpg2YMcXB2tiws4iVI4o7SDUMmPrcBM1CpRNQrzA4Gf06wFkvu+PBYsawrL1a261pQbNghsyVnVnxvZ5EplXvCnTe4CjisNevx22Jss0T0LCRqjxfRFw1xqXfhjdnZTQZowLghP7ZSnaHCTRjf2M5X+ZjbqIo3lKFz3qqao4=
  app: grox-mud
  on:
    repo: grox-org/mud
  run:
    - rake db:migrate
    - restart
